version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8081:8080
    entrypoint: '/opt/keycloak/bin/kc.sh'
    command: 'start-dev --import-realm'
    volumes:
      - ./main-realm.json:/opt/keycloak/data/import/main-realm.json
